import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/features/core/providers";

export const metadata: Metadata = {
  title: "OTB Hotels",
  description: "Generated by Rafee Jenkins",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
